@hostname = localhost
@port = 3000
@host = {{hostname}}:{{port}}
@contentType = application/json; charset=utf-8
###
GET http://{{host}}/
Content-Type: {{contentType}}

###
POST http://{{host}}/users
Content-Type: {{contentType}}

{"username":"Nui"}
###
GET http://{{host}}/3
Content-Type: {{contentType}}

###
GET http://{{host}}/4
Content-Type: {{contentType}}
